### ISSUE TITLE
The current release (0.0.2) does not accept -e environment variables

### ISSUE THREAD

**Issue by qualitymanifest** [jkrup/meteor-hero#3]
I kept getting the error "No MONGO_URL set so creating one on Heroku" despite having a `MONGO_URL` specified.

Looks like it wasn't implemented yet in [the 0.0.2 release](https://github.com/jkrup/meteor-hero/blob/a7c935a3e8fe99e92fcc5167f7b52fa2eae6c328/index.js#L83), but I can see that it [has been since](https://github.com/jkrup/meteor-hero/blob/392d80fb531318bc5c04b3278f524f13b1ec6125/commands/newDeploy.js#L67), just need to update the release.

I added the missing code to my local version and it works great - Thanks for creating this!

**Comment by jkrup** [comment]
I just pushed up v0.0.3. Please let me know if it works now after an `npm install -g meteor-hero`

**Comment by qualitymanifest** [comment]
Yep, all good now!
